language: scala
scala:
- 2.13.2
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
script: sbt ++$TRAVIS_SCALA_VERSION selenium:test || sbt ++$TRAVIS_SCALA_VERSION selenium:test
after_failure: ./support-frontend/scripts/post_test_results_to_chat.sh
