AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda/API gateway for creating Stripe Setup Intents

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Description: Returns a stripe setup intent token so we can get authorisation of a recurring payment on the client side
      FunctionName:
        !Sub stripe-intent-${Stage}
      Handler: com.gu.stripeIntent.Handler::handleRequest
      CodeUri:
        Bucket: support-workers-dist
        Key: !Sub support/${Stage}/stripe-intent/stripe-intent.jar
      MemorySize: 2048
      Runtime: java8
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:InvokeFunction
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/stripe-intent-${Stage}:log-stream:*"
        - Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource:
              - !Sub
                - arn:aws:s3:::gu-reader-revenue-private/stripe/${stripeConfig}-stripe-regular.private.conf
                - stripeConfig:
                    !FindInMap [ StageMap, !Ref Stage, StripeConfig ]
