{{name}}Lambda:
  Type: "AWS::Lambda::Function"
  Description: "{{description}}"
  Properties:
    {{> environmentVariables}}
    FunctionName: !Sub ${Stack}-{{name}}Lambda-${Stage}
    Handler: "com.gu.support.workers.lambdas.{{name}}::handleRequest"
    MemorySize: {{memorySize}}{{^memorySize}}1536{{/memorySize}}
    Role: !GetAtt [ LambdaExecutionRole, Arn ]
    Code:
      S3Bucket: support-workers-dist
      S3Key: !Sub support/${Stage}/support-workers/support-workers-{{> GITHUB_RUN_NUMBER}}.jar
    SnapStart:
      ApplyOn: PublishedVersions
    Runtime: "java21"
    Timeout: "60"
    Architectures:
      - x86_64

{{name}}AliasForLambda:
  Type: "AWS::Lambda::Alias"
  Properties:
    FunctionName: !Ref {{name}}Lambda
    FunctionVersion: !GetAtt [ {{name}}CurrentVersion, Version ]
    Name: SNAPSTART

{{name}}CurrentVersion:
  Type: "AWS::Lambda::Version"
  Properties:
    FunctionName: !Ref {{name}}Lambda
    Description: {{> GITHUB_RUN_NUMBER}}


