AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: API for acquisition events

Parameters:
  App:
    Description: Acquisition Events Api
    Type: String
    Default: acquisition-events-api
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist
  CertificateArn:
    Description: ARN of the certificate
    Type: String

Mappings:
  StageMap:
    CODE:
      DomainName: acquisition-events-code.support.guardianapis.com
      CorsOrigin: "'*'"
    PROD:
      DomainName: acquisition-events.support.guardianapis.com
      CorsOrigin: "'*'"

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Globals:
  Api:
    Cors:
      AllowOrigin: !FindInMap [ StageMap, !Ref Stage, CorsOrigin ]
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'*'"

Resources:

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: A lambda for acquisitions events api
      Runtime: java8.al2
      Handler: com.gu.acquisitionEventsApi.Lambda::handler
      MemorySize: 512
      Timeout: 300
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Effect: Allow
          Action: s3:GetObject
          Resource:
            - arn:aws:s3::*:membership-dist/*
      Events:
        AcquisitionEvent:
            Type: Api
            Properties:
                Path: '/acquisition'
                Method: post

  DomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      RegionalCertificateArn: # only for *.support.guardianapis.com
        !Ref CertificateArn
      DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      RestApiId: !Ref ServerlessRestApi # auto generated by the Transform
      DomainName: !Ref DomainName
      Stage: !Sub Prod
    DependsOn: ServerlessRestApiProdStage # auto generated by the Transform

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: support.guardianapis.com.
      Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      Comment: !Sub CNAME for acquisition events endpoints ${Stage}
      Type: CNAME
      TTL: '120'
      ResourceRecords:
        - !GetAtt [ DomainName, RegionalDomainName ]
