AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
    Description: Stage for the tables
    AllowedValues:
      - CODE
      - PROD

Mappings:
  StageMap:
    CODE:
      TableDEV: "redemption-codes-DEV-CODE"
      TableUAT: "redemption-codes-UAT-CODE"
      TablePROD: "redemption-codes-PROD-CODE"
    PROD:
      TableDEV: "redemption-codes-DEV"
      TableUAT: "redemption-codes-UAT"
      TablePROD: "redemption-codes-PROD"

Resources:
  RedemptionCodeDynamoTableDEV:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "redemptionCode"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "redemptionCode"
          KeyType: "HASH"
      TableName: !FindInMap [ StageMap, !Ref Stage, TableDEV ]
  RedemptionCodeDynamoTableUAT:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "redemptionCode"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "redemptionCode"
          KeyType: "HASH"
      TableName: !FindInMap [ StageMap, !Ref Stage, TableUAT ]
  RedemptionCodeDynamoTablePROD:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "redemptionCode"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "redemptionCode"
          KeyType: "HASH"
      TableName: !FindInMap [ StageMap, !Ref Stage, TablePROD ]
Outputs:
  DynamoArnOutDEV:
    Description: ARN for DEV dynamo table
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${RedemptionCodeDynamoTableDEV}
    Export:
      Name: !Sub ${AWS::StackName}-DynamoTableArnDEV
  DynamoArnOutUAT:
    Description: ARN for UAT dynamo table
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${RedemptionCodeDynamoTableUAT}
    Export:
      Name: !Sub ${AWS::StackName}-DynamoTableArnUAT
  DynamoArnOut:
    Description: ARN for PROD dynamo table
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${RedemptionCodeDynamoTablePROD}
    Export:
      Name: !Sub ${AWS::StackName}-DynamoTableArnPROD
