name: Chromatic
on:
  push:
jobs:
  upload-storybook:
    if: ${{ github.actor != 'gu-scala-steward-public-repos[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: support-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: guardian/actions-setup-node@v2.4.1

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - name: Cache dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: support-frontend

      - name: Install
        run: yarn
      - uses: chromaui/action@v1
        with:
          workingDir: support-frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: "build-storybook"
          exitOnceUploaded: true
          onlyChanged: "!(main)" # only turbosnap on non-main branches
