name: E2E
on:
  workflow_dispatch:
  pull_request:
    types: [labeled] # Only run when a PR is labeled with the 'Seen-on-PROD' label set by prout

concurrency:
  group: 'playwright-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event.label.name == 'Seen-on-PROD' }}
    name: Playwright
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env :
      BROWSERSTACK_USERNAME : ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY : ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      GOOGLE_CHAT_WEB_HOOK : ${{ secrets.GOOGLE_CHAT_WEB_HOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./support-e2e

      - name: Run Playwright
        run: yarn pw-browserstack-test
        working-directory: ./support-e2e

      - name: Notify on Failure
        if: ${{ failure() }}
        run: |
          echo "Tests have failed - calling webhook"
          failedWorkflowRun="https://github.com/guardian/support-frontend/actions/runs/$GITHUB_RUN_ID"
          curl -X POST -H 'Content-Type: application/json' '$GOOGLE_CHAT_WEB_HOOK' -d '{"text": "❌ The Playwright post deployment tests for support frontend have failed! <users/all> \n \n 👉 <'"$failedWorkflowRun"'|Workflow run> \n 🤖 <https://automate.browserstack.com/dashboard/v2/builds/31f35a1d9bccc9d45360aa7bfd651fcd9e1499d0|Browser stack test results> \n \n 📖 <https://github.com/guardian/support-frontend/wiki/Post-deployment-test-runbook|Check the runbook for a step by step guide>"}'

