name: Test Scala-steward PRs

on:
  pull_request:
    branches: [ main ]

env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
  Setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: guardian/actions-setup-node@main

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - name: Cache dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: support-frontend

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

  Typescript:
    needs: Setup
    name: Build Typescript
    defaults:
      run:
        working-directory: support-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: yarn

      - name: Build the html used for SSR pages
        run: yarn run build-ssr

      - name: Build assets
        run: yarn run build-prod

  Scala:
    needs: Typescript
    name: Build Scala
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: sbt test
