name: Test Scala-steward PRs

on:
  pull_request:

env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
  run_sbt_tests:
    if: github.actor == 'scala-steward'

    name: support-frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and run tests
        run: sbt test
