name: Build stripe-patrons-data

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  support_frontend_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: stripe-patrons-data build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node for CDK
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: cdk/yarn.lock

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt

      - name: Build
        run: |
          sbt "project stripe-patrons-data" assembly

      - name: Upload to RiffRaff
        uses: guardian/actions-riff-raff@v2
        with:
          app: stripe-patrons-data
          buildNumberOffset: 3000
          config: |
            stacks:
              - support
            regions:
              - eu-west-1
            allowedStages:
              - CODE
              - PROD
            deployments:
              cfn:
                type: cloud-formation
                app: stripe-patrons-data
                parameters:
                  templateStagePaths:
                    CODE: StripePatronsData-CODE.template.json
                    PROD: StripePatronsData-CODE.template.json

              stripe-patrons-data:
                type: aws-lambda
                parameters:
                  bucket: membership-dist
                  functionNames:
                    - stripe-patrons-data-
                    - stripe-patrons-data-cancelled-
                    - stripe-patrons-data-sign-up-
                  fileName: ${{ github.run_number }}.jar
                  prefixStack: false

          contentDirectories: |
            stripe-patrons-data:
              - stripe-patrons-data/target/scala-2.13/${{ github.run_number }}.zip
            cfn:
              - cdk/cdk.out/StripePatronsData-CODE.template.json
              - cdk/cdk.out/StripePatronsData-CODE.template.json
