name: support-frontend - typescript

on:
  push:
    paths:
      - support-frontend/**

jobs:
  support_frontend_build:
    name: support-frontend - typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
          cache-dependency-path: support-frontend/yarn.lock

      - name: Install
        run: yarn
        working-directory: support-frontend

      - name: Type check
        run: yarn tsc
        working-directory: support-frontend
