name: Build support-frontend
on:
  push:
    branches:
      - main
env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
    build_typescript:
      name: Build the Typescript part of the application
      defaults:
        run:
          working-directory: support-frontend
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Node
          uses: guardian/actions-setup-node@main

        # Cache npm dependencies using https://github.com/bahmutov/npm-install
        - name: Cache dependencies
          uses: bahmutov/npm-install@v1
          with:
            working-directory: support-frontend

        - name: Install
          run: yarn

        - name: Generate production build for github action
          run: yarn build-github-action

        - name: Build the html used for SSR pages
          run: yarn run build-ssr

        - name: Build assets
          run: yarn run build-prod

        - name: Set up Java
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Build and upload to RiffRaff
          run: sbt "project support-frontend" clean test riffRaffUpload
