name: " Support Frontend Post Deployment Tests Using Playwright Lambda"
on: [push]
jobs:
  CI:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'support-lambdas/support-post-deployment-tests/.nvmrc'
          cache: "yarn"
          cache-dependency-path: |
            support-lambdas/support-post-deployment-tests/yarn.lock
      - run: |
          yarn install
          yarn build
          yarn postbuild
        working-directory: support-lambdas/support-post-deployment-tests
      - name: CDK synth
        run: |
          yarn install
          yarn tsc
          yarn lint
          yarn test
          yarn synth
        working-directory: support-lambdas/support-post-deployment-tests/packages/cdk
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v2
        with:
          configPath: ./support-lambdas/support-post-deployment-tests/riff-raff.yaml
          projectName: Support::support-frontend-post-deployment-tests
          contentDirectories: |
            cdk.out:
              - support-lambdas/support-post-deployment-tests/packages/cdk/cdk.out/support-frontend-post-deployment-tests-lambda-CODE.template.json
              - support-lambdas/support-post-deployment-tests/packages/cdk/cdk.out/support-frontend-post-deployment-tests-lambda-PROD.template.json
            support-frontend-post-deployment-tests-lambda:
              - support-lambdas/support-post-deployment-tests/packages/lambda/dist/support-frontend-post-deployment-tests.zip

