name: support-frontend - prettier

on:
  push:
    paths:
      - support-frontend/**

jobs:
  support_frontend_build:
    name: support-frontend - prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
          cache-dependency-path: support-frontend/yarn.lock

      - name: Install
        run: yarn
        working-directory: support-frontend

      - name: Prettier check
        run: yarn prettier:check
        working-directory: support-frontend
